// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkC6sOHY0hHa5YIpdcRr8dFM_1q2f9rg',
    appId: '1:548384663008:web:b1e66461de90b30e77b785',
    messagingSenderId: '548384663008',
    projectId: 'enanoza-finals-lab-act-2',
    authDomain: 'enanoza-finals-lab-act-2.firebaseapp.com',
    storageBucket: 'enanoza-finals-lab-act-2.firebasestorage.app',
    measurementId: 'G-BLXZTPDC14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4R8PCTKBm3-KYqD4C-TDQnvmoP8pKWVU',
    appId: '1:548384663008:android:0b98250c9307a35277b785',
    messagingSenderId: '548384663008',
    projectId: 'enanoza-finals-lab-act-2',
    storageBucket: 'enanoza-finals-lab-act-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4ODf13HNBCw-LxoOGXGmLxm68KOpk6hM',
    appId: '1:548384663008:ios:442633d1ee8f9f5c77b785',
    messagingSenderId: '548384663008',
    projectId: 'enanoza-finals-lab-act-2',
    storageBucket: 'enanoza-finals-lab-act-2.firebasestorage.app',
    iosBundleId: 'com.olfu.enanozaFinalsLabAct2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4ODf13HNBCw-LxoOGXGmLxm68KOpk6hM',
    appId: '1:548384663008:ios:442633d1ee8f9f5c77b785',
    messagingSenderId: '548384663008',
    projectId: 'enanoza-finals-lab-act-2',
    storageBucket: 'enanoza-finals-lab-act-2.firebasestorage.app',
    iosBundleId: 'com.olfu.enanozaFinalsLabAct2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOkC6sOHY0hHa5YIpdcRr8dFM_1q2f9rg',
    appId: '1:548384663008:web:57970011eafe7b5377b785',
    messagingSenderId: '548384663008',
    projectId: 'enanoza-finals-lab-act-2',
    authDomain: 'enanoza-finals-lab-act-2.firebaseapp.com',
    storageBucket: 'enanoza-finals-lab-act-2.firebasestorage.app',
    measurementId: 'G-B82QQLH9ZY',
  );
}